urg_node2:
  ros__parameters:
    # ip_address: "192.168.0.10"
    # ip_port: 10940
    serial_port: "/dev/ttyACM0"
    serial_baud: 115200
    frame_id: "base_laser_link"
    calibrate_time: true
    synchronize_time: true
    publish_intensity: false
    publish_multiecho: false
    error_limit: 4
    error_reset_period : 5.0
    diagnostics_tolerance: 0.05
    diagnostics_window_time: 5.0
    time_offset: 0.0
    angle_max: 1.5707963
    angle_min: -1.5707963
    cluster: 0
    skip: 1